name: Auto Update

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-lastest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update files
        run: |


      - name: Commit and push changes
        run: |
          git add .
          git config --global user.name 'Nhom1'
          git commit -m "Auto update data" || echo "No changes to commit"
          git push
