name: Auto Update

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-lastest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update files
        run: |

